apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: namespacejanitor-operator-system
data:
  config.yaml: |
    region: ""
    lifecycle:
      creationNotification: true
      yellowThreshold: "72h"
      redThreshold: "336h"
      finalWarningThreshold: "720h"
      deleteThreshold: "816h"
      excludeNamespaces:
        - "^openshift-.*"
        - "^kube-.*"
        - "^default$"
        - "^kube-public$"
        - "^kube-node-lease$"
        - "^snappcloud-.*"
        - ".*-operator-system$"
        - "^argocd$"
        - "^monitoring$"
        - "^cert-manager$"
    notifications:
      mattermost:
        webhook: "https://chat.snapp.services/hooks/4wx3ya77ojyt78hpgchbofo43a"
      kafka:
        broker: ""
        topic: "namespace-janitor-notifications"
        group: "namespace-janitor-group"
