apiVersion: v1
kind: ConfigMap
metadata:
  name: config
  namespace: namespacejanitor-operator-system
data:
  config.yaml: |
    lifecycle:
      creationNotification: true
      yellowThreshold: "72h"
      redThreshold: "336h"
      finalWarningThreshold: "720h"
      deleteThreshold: "816h"
    notifications:
      mattermost:
        webhook: "https://chat.snapp.services/hooks/4wx3ya77ojyt78hpgchbofo43a"
      kafka:
        broker: ""
        topic: "namespace-janitor-notifications"
        group: "namespace-janitor-group"
