---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snappcloud.snappcloud.io
  resources:
  - namespacejanitors
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - snappcloud.snappcloud.io
  resources:
  - namespacejanitors/finalizers
  verbs:
  - update
- apiGroups:
  - snappcloud.snappcloud.io
  resources:
  - namespacejanitors/status
  verbs:
  - get
  - patch
  - update
