apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/name: namespacejanitor
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/instance: system
    app.kubernetes.io/component: manager
    app.kubernetes.io/created-by: namespacejanitor
    app.kubernetes.io/part-of: namespacejanitor
  name: controller-manager
  namespace: namespacejanitor-operator-system
