version: 2

run:
  timeout: 5m

issues:
  exclude-dirs:
    - ^test$
  exclude-files:
    - "_test\\.go$"
    - "test/utils/utils\\.go$"
  exclude-rules:
    - linters:
        - staticcheck
      text: "ST1001"
      path: "test/utils/utils\\.go"

linters-settings:
  staticcheck:
    checks:
      - all
      - "-ST1001"

output:
  format: colored-line-number